Rarping: rarping/rarping/rarping.h File Reference
rarping/rarping/rarping.h File Reference
Rarping - send RARP REQUEST to a neighbour host.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/time.h>
#include <signal.h>
#include <errno.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <arpa/inet.h>
#include <linux/if_ether.h>
#include <sys/ioctl.h>
#include <net/if.h>
#include <linux/if_packet.h>
Data Structures
struct rarpPacket_t
this describes a RARP packet
struct etherPacket_t
full ethernet trame, MAC headers + RARP packet as described above
struct opt_t
Contains options/informations given trought command line.
Defines
#define VERSION "rarping 0.1 beta"
#define IS_ROOT (((getuid() != 0) || (geteuid() != 0)) ? 0 : 1)
#define ABS(i) (((i) >= 0) ? (i) : -(i))
#define ERR_ARG_PARSING -1
#define ETH_TYPE_RARP 0x8035
#define IP_PROTO 0x800
#define HW_TYPE_ETHERNET 0x01
#define RARP_OPCODE_REQUEST 0x03
#define RARP_OPCODE_REPLY 0x0004
#define IP_ADDR_SIZE 15
#define MAC_ADDR_SIZE 17
#define MS_DEFAULT_DELAY 1000
Functions
void usage (void)
Usage() prints out some help to craft a correct command line.
void parseTimeout (struct timeval *pstr_timeout, char *pch_arg)
set the send/recv timeout from command line to integers
signed char argumentManagement (long l_argc, char **ppch_argv, opt_t *pstr_argsDest)
Parse given arguments and fill an opt structure.
void initOptionsDefault (opt_t *pstr_args)
set options to their default values
void signalHandler (void)
turn on the signal handler
signed char performRequests (const opt_t *pstr_argsDest)
perform RARP requests the way defined by user
signed char craftPacket (etherPacket_t *pstr_packet, const opt_t *str_destArgs, struct sockaddr_ll *pstr_device, long l_socket)
find out and packs the datas we'll send
signed char getLowLevelInfos (struct sockaddr_ll *pstr_device, char *pch_ifaceName, long l_socket)
fills a sockaddr_ll struct whith hardware address and interface index of a selected device
signed char getLocalHardwareAddress (long l_socket, char *pch_ifaceName, unsigned char *puc_mac)
fill hw_addr field of pstr_device with local MAC address
unsigned long getIfaceIndex (char *pch_ifName, long l_socket)
get Index of used network interface
signed char sendProbe (long l_socket, etherPacket_t *pstr_packet, struct sockaddr_ll *pstr_device)
send RARP requests into the wild
unsigned char getAnswer (long l_socket, struct sockaddr_ll *pstr_device, const struct timeval str_sendingMoment)
wait for an answer and, if receive any, parse it
void printOutReply (etherPacket_t *pstr_reply, const struct timeval str_delay)
check if received packet seems correct (or not) it and print its main informations
signed char parse (etherPacket_t *pstr_reply, char tch_replySrcIp[], char tch_replySrcHwAddr[], char tch_replyHwAddr[], char tch_replyAddrIp[])
parse an reply packet and fill strings to print results out in a clean way
signed char footer (unsigned long ul_sentPackets, unsigned long ul_receivedPackets)
print out a summary of what happened
signed long openRawSocket (struct timeval str_timeout)
open a raw socket and set timeout on sending and reception
signed char loop (const opt_t *pstr_argsDest, etherPacket_t *pstr_packet, struct sockaddr_ll *pstr_device, long l_socket)
sending loop : send packets as many times as wanted
signed char setTargetIpAddress (unsigned char *puc_targetIpAddress, const opt_t *pstr_argsDest)
fills target protocol address in sent packets according to user choices (option -a)
signed char setSenderIpAddress (unsigned char *puc_senderIpAddress, const opt_t *pstr_argsDest, long l_socket)
set source IP address in packets to wanted values
struct timeval timeDiff (const struct timeval str_beginning, const struct timeval str_termination)
return elapsed time between two given moments
void printTime_ms (const struct timeval str_time)
print out elapsed time from a timeval structure to usual format in milliseconds
void rarpingOnExit (int sig)
perform a clean exit, calling statistics function and closing the socket
Detailed Description
Rarping - send RARP REQUEST to a neighbour host.
Author
henri.doreau
Date
2008-07-07 23:27:08 +0200 (lun, 07 jui 2008)
Revision
37
Definition in file rarping.h.
Define Documentation
#define ABS (i) (((i) >= 0) ? (i) : -(i))
send positive part of (i)
Definition at line 72 of file rarping.h.
Referenced by argumentManagement().
#define ERR_ARG_PARSING -1
returned value if argument parsing fails
Definition at line 80 of file rarping.h.
Referenced by argumentManagement().
#define ETH_TYPE_RARP 0x8035
ether type for the rarp protocol
Definition at line 86 of file rarping.h.
Referenced by craftPacket(), and printOutReply().
#define HW_TYPE_ETHERNET 0x01
hardware type (ethernet)
Definition at line 94 of file rarping.h.
Referenced by craftPacket().
#define IP_ADDR_SIZE 15
max length of an IP address in standard notation
Definition at line 104 of file rarping.h.
Referenced by parse(), and printOutReply().
#define IP_PROTO 0x800
IP protocole number
Definition at line 91 of file rarping.h.
Referenced by craftPacket().
#define IS_ROOT (((getuid() != 0) || (geteuid() != 0)) ? 0 : 1)
check if privilieges are granted
Definition at line 68 of file rarping.h.
Referenced by openRawSocket().
#define MAC_ADDR_SIZE 17
max length of a MAC address in standard notation
Definition at line 107 of file rarping.h.
Referenced by parse(), and printOutReply().
#define MS_DEFAULT_DELAY 1000
number of milliseconds to sleep between two probes
Definition at line 117 of file rarping.h.
Referenced by initOptionsDefault().
#define RARP_OPCODE_REPLY 0x0004
operation code for a RARP reply
Definition at line 100 of file rarping.h.
Referenced by argumentManagement(), and printOutReply().
#define RARP_OPCODE_REQUEST 0x03
operation code for a RARP request
Definition at line 97 of file rarping.h.
Referenced by initOptionsDefault().
#define VERSION "rarping 0.1 beta"
Software Version
Definition at line 56 of file rarping.h.
Referenced by argumentManagement().
Function Documentation
signed char argumentManagement (long l_argc, char ** ppch_argv, opt_t * pstr_argsDest)
Parse given arguments and fill an opt structure.
Parameters:
l_argc is the number of arguments contained in command line when launching the soft
ppch_argv is an array of pointers to the arguments given
pst_argsDest is a structure where are stored user defined options
Returns:
Error code according to the execution of the function
Return values:
0 The function ends normally
ERR_ARG_PARSING (< 0) can't parse command line
See also:
opt_t
Definition at line 72 of file rarping.c.
References ABS, ERR_ARG_PARSING, initOptionsDefault(), parseTimeout(), opt_t::pch_askedHwAddr, opt_t::pch_iface, opt_t::pch_IpAddrRarpReplies, opt_t::pch_spoofedLocalIpAddress, RARP_OPCODE_REPLY, opt_t::str_timeout, opt_t::uc_choosenOpCode, opt_t::uc_exitOnReply, opt_t::uc_unlimitedRetries, opt_t::ul_count, opt_t::ul_maximumRetries, opt_t::ul_waitingMilliSeconds, and VERSION.
signed char craftPacket (etherPacket_t * pstr_packet, const opt_t * str_destArgs, struct sockaddr_ll * pstr_device, long l_socket)
find out and packs the datas we'll send
Parameters:
pstr_packet points to a struct this function will fill with raw datas to send
pch_ifaceName is a string containing the interface to use
pstr_device points to a structure that will contain low level informations needed
pch_askedHwAddr (string) contains the hardware address to request about
l_socket is the raw socket opened before
Returns:
Error code according to the execution of the function
Return values:
0 the function ends normally
-1 bad interface given
-2 bad hardware address given, or unrecognized format
Definition at line 273 of file rarping.c.
References ETH_TYPE_RARP, getLowLevelInfos(), HW_TYPE_ETHERNET, IP_PROTO, opt_t::pch_askedHwAddr, opt_t::pch_iface, setSenderIpAddress(), setTargetIpAddress(), etherPacket_t::str_packet, opt_t::uc_choosenOpCode, rarpPacket_t::uc_hwLen, rarpPacket_t::uc_protoLen, etherPacket_t::uct_destHwAddr, etherPacket_t::uct_senderHwAddr, rarpPacket_t::uct_srcHwAddr, rarpPacket_t::uct_srcIpAddr, rarpPacket_t::uct_targetIpAddr, etherPacket_t::us_ethType, rarpPacket_t::us_hwType, rarpPacket_t::us_opcode, and rarpPacket_t::us_protoType.
Referenced by performRequests().
signed char footer (unsigned long ul_sentPackets, unsigned long ul_receivedPackets)
print out a summary of what happened
Parameters:
ul_sentPackets number of sent packets
ul_receivedPackets number of received packets
Returns:
Error code according to the execution of the function
Return values:
0 the function ends normally
-1 not any packet were sent
Definition at line 506 of file rarping.c.
Referenced by performRequests(), and rarpingOnExit().
unsigned char getAnswer (long l_socket, struct sockaddr_ll * pstr_device, const struct timeval str_sendingMoment)
wait for an answer and, if receive any, parse it
Parameters:
l_socket is the raw socket opened before
pstr_device low level informations to receive datas without any encapsulation
str_sendingMoment is used to chronometer and print out how fast the received replies are
Returns:
the number of replies received
Definition at line 408 of file rarping.c.
References printOutReply(), and timeDiff().
Referenced by loop().
unsigned long getIfaceIndex (char * pch_ifName, long l_socket)
get Index of used network interface
Parameters:
pch_ifName (string) contains the name of the selected interface as provided by user
l_socket raw socket opened befor
Returns:
interface index
Definition at line 372 of file rarping.c.
Referenced by getLowLevelInfos().
signed char getLocalHardwareAddress (long l_socket, char * pch_ifaceName, unsigned char * puc_mac)
fill hw_addr field of pstr_device with local MAC address
Parameters:
l_socket raw socket opened befor
pch_ifaceName (string) contains the name of the selected interface as provided by user
mac string filled with the hardware address of the selected interface
Returns:
Error code according to the execution of the function
Return values:
0 the function ends normally
-1 can't find MAC address
Definition at line 347 of file rarping.c.
Referenced by getLowLevelInfos().
signed char getLowLevelInfos (struct sockaddr_ll * pstr_device, char * pch_ifaceName, long l_socket)
fills a sockaddr_ll struct whith hardware address and interface index of a selected device
Parameters:
pstr_device contains provides a low level device independant access
pch_ifaceName (string) contains the hardware address to request about
l_socket raw socket opened before
Returns:
Error code according to the execution of the function
Return values:
0 the function ends normally
-1 if function can't provide low level infos
Definition at line 319 of file rarping.c.
References getIfaceIndex(), and getLocalHardwareAddress().
Referenced by craftPacket().
void initOptionsDefault (opt_t * pstr_args)
set options to their default values
Parameters:
pstr_argsDest points to the structure where user choices are stored
See also:
opt_t
Definition at line 161 of file rarping.c.
References MS_DEFAULT_DELAY, opt_t::pch_askedHwAddr, opt_t::pch_iface, opt_t::pch_IpAddrRarpReplies, opt_t::pch_spoofedLocalIpAddress, RARP_OPCODE_REQUEST, opt_t::str_timeout, opt_t::uc_choosenOpCode, opt_t::uc_exitOnReply, opt_t::uc_unlimitedRetries, opt_t::ul_count, opt_t::ul_maximumRetries, and opt_t::ul_waitingMilliSeconds.
Referenced by argumentManagement().
signed char loop (const opt_t * pstr_argsDest, etherPacket_t * pstr_packet, struct sockaddr_ll * pstr_device, long l_socket)
sending loop : send packets as many times as wanted
Parameters:
pstr_argsDest points to the structure which contains user inputs
pstr_packet points to the packet to send
sockaddr_ll low level information to send datas without encapsulation
l_socket Raw socket opened before
Returns:
Error code according to the execution of the function
Return values:
0 the function ends normally
Definition at line 561 of file rarping.c.
References getAnswer(), sendProbe(), opt_t::uc_exitOnReply, opt_t::uc_unlimitedRetries, opt_t::ul_count, opt_t::ul_maximumRetries, and opt_t::ul_waitingMilliSeconds.
Referenced by performRequests().
signed long openRawSocket (struct timeval str_timeout)
open a raw socket and set timeout on sending and reception
Parameters:
none
Returns:
return code of socket() : > is the socket we want, < 0 if an error ocured
Definition at line 532 of file rarping.c.
References IS_ROOT.
Referenced by performRequests().
signed char parse (etherPacket_t * pstr_reply, char tch_replySrcIp[], char tch_replySrcHwAddr[], char tch_replyHwAddr[], char tch_replyAddrIp[])
parse an reply packet and fill strings to print results out in a clean way
Parameters:
pstr_reply datas to parse (received packet)
tch_replySrcIp formatted string containing IP address of the sender of the reply
tch_replySrcHwAddr formatted string containing MAC address of the sender of the reply
tch_replyHwAddr formatted string containing MAC address we were requesting
tch_replyAddrIp formatted string containing IP address we were asking for
Returns:
Error code according to the execution of the function
Return values:
0 the function ends normally
Definition at line 473 of file rarping.c.
References IP_ADDR_SIZE, MAC_ADDR_SIZE, etherPacket_t::str_packet, rarpPacket_t::uct_srcIpAddr, and rarpPacket_t::uct_targetIpAddr.
Referenced by printOutReply().
void parseTimeout (struct timeval * pstr_timeout, char * pch_arg)
set the send/recv timeout from command line to integers
Parameters:
pstr_timeout vdestination of parsed argument
pch_arg timeout, as string, given by user through command line
Returns:
none
Definition at line 199 of file rarping.c.
Referenced by argumentManagement().
signed char performRequests (const opt_t * pstr_argsDest)
perform RARP requests the way defined by user
Parameters:
pst_argsDest is an opt_t structure which contains user defined options
Returns:
Error code according to the execution of the function
Return values:
0 The function ends normally
-1 can't open RAW socket
-3 can't craft packet
-4 error when closing socket
Definition at line 228 of file rarping.c.
References craftPacket(), footer(), loop(), openRawSocket(), and opt_t::str_timeout.
void printOutReply (etherPacket_t * pstr_reply, const struct timeval str_delay)
check if received packet seems correct (or not) it and print its main informations
Parameters:
pstr_reply points to the received packet
str_delay is the time elapsed between sending and reeption
Definition at line 448 of file rarping.c.
References ETH_TYPE_RARP, IP_ADDR_SIZE, MAC_ADDR_SIZE, parse(), printTime_ms(), RARP_OPCODE_REPLY, etherPacket_t::str_packet, etherPacket_t::us_ethType, and rarpPacket_t::us_opcode.
Referenced by getAnswer().
void printTime_ms (const struct timeval str_time)
print out elapsed time from a timeval structure to usual format in milliseconds
Parameters:
str_time contains a number of seconds and microseconds
Definition at line 706 of file rarping.c.
Referenced by printOutReply().
void rarpingOnExit (int sig)
perform a clean exit, calling statistics function and closing the socket
Parameters:
int sig received signal that force rarping to exit
Definition at line 712 of file rarping.c.
References footer().
Referenced by signalHandler().
signed char sendProbe (long l_socket, etherPacket_t * pstr_packet, struct sockaddr_ll * pstr_device)
send RARP requests into the wild
Parameters:
l_socket raw socket opened before
pstr_packet raw datas to send
pstr_device low level informations to send datas without any encapsulation
Returns:
Error code according to the execution of the function
Return values:
0 the function ends normally
Returns:
-1 can't perform sending
Definition at line 393 of file rarping.c.
Referenced by loop().
signed char setSenderIpAddress (unsigned char * puc_senderIpAddress, const opt_t * pstr_argsDest, long l_socket)
set source IP address in packets to wanted values
Parameters:
puc_senderIpAddress field to fill
pstr_argsDest user options
l_socket socket descriptor to perform ioctl calls (to find ut local real IP address)
Return values:
error code according to the execution of the function
Returns:
0 the function ends normally
1 an error occured : IP address set to its default value : 0.0.0.0
Definition at line 643 of file rarping.c.
References opt_t::pch_iface, and opt_t::pch_spoofedLocalIpAddress.
Referenced by craftPacket().
signed char setTargetIpAddress (unsigned char * puc_targetIpAddress, const opt_t * pstr_argsDest)
fills target protocol address in sent packets according to user choices (option -a)
Parameters:
puc_targetIpAddress target protocol address field in crafted packet
pstr_argsDest choosen user's inputs
Returns:
Error code according to the execution of the function
Return values:
0 the function ends normally
Definition at line 610 of file rarping.c.
References opt_t::pch_IpAddrRarpReplies.
Referenced by craftPacket().
struct timeval timeDiff (const struct timeval str_beginning, const struct timeval str_termination) [read]
return elapsed time between two given moments
Parameters:
str_beginning starting point
str_termination ending point
Returns:
struct timeval containing elapsed time from str_beginning to str_termination
Definition at line 694 of file rarping.c.
Referenced by getAnswer().